/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oopgroup3.e_exam_client;


import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Kyle
 */

/**
 * Control E_Exam_Client GUI components
 * @author tri.le
 */
public class E_Exam_Client_GUI extends javax.swing.JFrame {

    private final CardLayout cardLayoutManager;
    private boolean  doonce = true;
    /**
     * Creates new form EExam_GUI
     */
    public E_Exam_Client_GUI() {
        initComponents();
       
        cardLayoutManager = (CardLayout)cardlayout_container.getLayout();
        
        cardlayout_container.add(login_panel, "login");
        cardlayout_container.add(register_panel, "register");
        cardlayout_container.add(student_panel, "student");
        cardlayout_container.add(teacher_panel, "teacher");
        cardlayout_container.add(exam_panel, "exam");
        cardlayout_container.add(examCreation_panel, "createExam");
        cardlayout_container.add(examEdit_panel, "editExam");
        cardlayout_container.add(keyExam_panel, "keyExam");
        cardlayout_container.add(teacherAssignExams_panel, "assignExam");
        cardlayout_container.add(studentGrade_panel, "studentGrades");
        
        cardLayoutManager.show(cardlayout_container, "login");
        setTitle("E-Exam");
        pack();
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cardlayout_container = new javax.swing.JPanel();
        login_panel = new javax.swing.JPanel();
        username_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        cancel_login_btn = new javax.swing.JButton();
        username_txtField = new javax.swing.JTextField();
        password_txtField = new javax.swing.JPasswordField();
        newUserRegisterBtn = new javax.swing.JButton();
        register_panel = new javax.swing.JPanel();
        registerUsername_lbl = new javax.swing.JLabel();
        registerPassword_lbl = new javax.swing.JLabel();
        registerConfirmPassword_lbl = new javax.swing.JLabel();
        register_btn = new javax.swing.JButton();
        register_cancel_btn = new javax.swing.JButton();
        registerUsername_txtField = new javax.swing.JTextField();
        registerPassword_txtField = new javax.swing.JPasswordField();
        registerPasswordConfirm_txtField = new javax.swing.JPasswordField();
        user_type_comboBox = new javax.swing.JComboBox<>();
        user_type_lbl = new javax.swing.JLabel();
        register_incorrectPass_label = new javax.swing.JLabel();
        student_panel = new javax.swing.JPanel();
        studentBackToLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableStudentExams = new javax.swing.JList<>();
        welcomeLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        studentTakeExamBtn = new javax.swing.JButton();
        viewGradesBtn = new javax.swing.JButton();
        teacher_panel = new javax.swing.JPanel();
        teacherBackToLogin = new javax.swing.JButton();
        createExamBtn = new javax.swing.JButton();
        editExamBtn = new javax.swing.JButton();
        deleteExamBtn = new javax.swing.JButton();
        keyExamBtn = new javax.swing.JButton();
        assignExamButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        availableTeacherExams = new javax.swing.JList<>();
        exam_panel = new javax.swing.JPanel();
        examScrollPane = new javax.swing.JScrollPane();
        examFormContainer = new javax.swing.JPanel();
        submitStudentExam = new javax.swing.JButton();
        cancelStudentExam = new javax.swing.JButton();
        examCreation_panel = new javax.swing.JPanel();
        trueFalseFormAddBtn = new javax.swing.JButton();
        multipleChoiceFormAddBtn = new javax.swing.JButton();
        examCreationBackBtn = new javax.swing.JButton();
        createExamFormBtn = new javax.swing.JButton();
        examFormBuilder_scrollPane = new javax.swing.JScrollPane();
        examFormBuilder_panel = new javax.swing.JPanel();
        createExamNameTextField = new javax.swing.JTextField();
        examNameLbl = new javax.swing.JLabel();
        examEdit_panel = new javax.swing.JPanel();
        trueFalseFormAddEditBtn = new javax.swing.JButton();
        multipleChoiceFormAddEditBtn = new javax.swing.JButton();
        editReturnToTeacherPanelBtn = new javax.swing.JButton();
        editExamFormBtn = new javax.swing.JButton();
        examFormEditor_scrollPane = new javax.swing.JScrollPane();
        examFormEditor_panel = new javax.swing.JPanel();
        studentGrade_panel = new javax.swing.JPanel();
        examGrade_scrollpane = new javax.swing.JScrollPane();
        examGradeJList = new javax.swing.JList<>();
        cancelGradesBtn = new javax.swing.JButton();
        keyExam_panel = new javax.swing.JPanel();
        examFormKey_scrollPane = new javax.swing.JScrollPane();
        examFormKey_panel = new javax.swing.JPanel();
        submitKeyBtn = new javax.swing.JButton();
        cancelKeyBtn = new javax.swing.JButton();
        teacherAssignExams_panel = new javax.swing.JPanel();
        assignedStudents_scrollpane = new javax.swing.JScrollPane();
        assignedStudents_jlist = new javax.swing.JList<>();
        studentsComboBox = new javax.swing.JComboBox<>();
        cancelAssignExamBtn = new javax.swing.JButton();
        assignStudentExamBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardlayout_container.setLayout(new java.awt.CardLayout());

        login_panel.setLayout(new java.awt.GridBagLayout());

        username_lbl.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 5);
        login_panel.add(username_lbl, gridBagConstraints);

        password_lbl.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 62, 0, 5);
        login_panel.add(password_lbl, gridBagConstraints);

        login_btn.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(0, 58, 0, 90);
        login_panel.add(login_btn, gridBagConstraints);

        cancel_login_btn.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 65, 0, 84);
        login_panel.add(cancel_login_btn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 88);
        login_panel.add(username_txtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 88);
        login_panel.add(password_txtField, gridBagConstraints);

        newUserRegisterBtn.setText("Register");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 65, 0, 84);
        login_panel.add(newUserRegisterBtn, gridBagConstraints);

        cardlayout_container.add(login_panel, "card2");

        register_panel.setLayout(new java.awt.GridBagLayout());

        registerUsername_lbl.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        register_panel.add(registerUsername_lbl, gridBagConstraints);

        registerPassword_lbl.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        register_panel.add(registerPassword_lbl, gridBagConstraints);

        registerConfirmPassword_lbl.setText("Confirm Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        register_panel.add(registerConfirmPassword_lbl, gridBagConstraints);

        register_btn.setText("Register");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        register_panel.add(register_btn, gridBagConstraints);

        register_cancel_btn.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        register_panel.add(register_cancel_btn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        register_panel.add(registerUsername_txtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        register_panel.add(registerPassword_txtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        register_panel.add(registerPasswordConfirm_txtField, gridBagConstraints);

        user_type_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        register_panel.add(user_type_comboBox, gridBagConstraints);

        user_type_lbl.setText("User Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        register_panel.add(user_type_lbl, gridBagConstraints);

        register_incorrectPass_label.setForeground(new java.awt.Color(204, 0, 0));
        register_incorrectPass_label.setText("Incorrect password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        register_panel.add(register_incorrectPass_label, gridBagConstraints);

        cardlayout_container.add(register_panel, "card3");

        student_panel.setLayout(new java.awt.GridBagLayout());

        studentBackToLogin.setText("Logout");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        student_panel.add(studentBackToLogin, gridBagConstraints);

        availableStudentExams.setModel(new DefaultListModel<String>());
        jScrollPane1.setViewportView(availableStudentExams);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.25;
        student_panel.add(jScrollPane1, gridBagConstraints);

        welcomeLbl.setText("Welcome to E-Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        student_panel.add(welcomeLbl, gridBagConstraints);

        usernameLbl.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        student_panel.add(usernameLbl, gridBagConstraints);

        studentTakeExamBtn.setText("Take Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        student_panel.add(studentTakeExamBtn, gridBagConstraints);

        viewGradesBtn.setText("View Grades");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        student_panel.add(viewGradesBtn, gridBagConstraints);

        cardlayout_container.add(student_panel, "card4");

        teacher_panel.setLayout(new java.awt.GridBagLayout());

        teacherBackToLogin.setText("Logout");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teacher_panel.add(teacherBackToLogin, gridBagConstraints);

        createExamBtn.setText("Create Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teacher_panel.add(createExamBtn, gridBagConstraints);

        editExamBtn.setText("Edit Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teacher_panel.add(editExamBtn, gridBagConstraints);

        deleteExamBtn.setText("Delete Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teacher_panel.add(deleteExamBtn, gridBagConstraints);

        keyExamBtn.setText("Key Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teacher_panel.add(keyExamBtn, gridBagConstraints);

        assignExamButton.setText("Assign Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 85, 0);
        teacher_panel.add(assignExamButton, gridBagConstraints);

        availableTeacherExams.setModel(new DefaultListModel<String>());
        jScrollPane2.setViewportView(availableTeacherExams);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.85;
        gridBagConstraints.weighty = 1.0;
        teacher_panel.add(jScrollPane2, gridBagConstraints);

        cardlayout_container.add(teacher_panel, "card5");

        exam_panel.setLayout(new java.awt.GridBagLayout());

        examFormContainer.setPreferredSize(new java.awt.Dimension(366, 222));
        examFormContainer.setLayout(new java.awt.GridLayout(0, 1));
        examScrollPane.setViewportView(examFormContainer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        exam_panel.add(examScrollPane, gridBagConstraints);

        submitStudentExam.setText("Submit Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 0);
        exam_panel.add(submitStudentExam, gridBagConstraints);

        cancelStudentExam.setText("Cancel Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 70);
        exam_panel.add(cancelStudentExam, gridBagConstraints);

        cardlayout_container.add(exam_panel, "card6");

        examCreation_panel.setLayout(new java.awt.GridBagLayout());

        trueFalseFormAddBtn.setText("True / False Form");
        trueFalseFormAddBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.15;
        examCreation_panel.add(trueFalseFormAddBtn, gridBagConstraints);

        multipleChoiceFormAddBtn.setText("Multiple Choice Form");
        multipleChoiceFormAddBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.weightx = 0.15;
        examCreation_panel.add(multipleChoiceFormAddBtn, gridBagConstraints);

        examCreationBackBtn.setText("Back To Teacher Panel");
        examCreationBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examCreationBackBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        examCreation_panel.add(examCreationBackBtn, gridBagConstraints);

        createExamFormBtn.setText("Create Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        examCreation_panel.add(createExamFormBtn, gridBagConstraints);

        examFormBuilder_scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        examFormBuilder_scrollPane.setHorizontalScrollBar(null);
        examFormBuilder_scrollPane.setPreferredSize(new java.awt.Dimension(525, 650));

        examFormBuilder_panel.setLayout(new java.awt.GridLayout(0, 1, 2, 4));
        examFormBuilder_scrollPane.setViewportView(examFormBuilder_panel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.85;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        examCreation_panel.add(examFormBuilder_scrollPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        examCreation_panel.add(createExamNameTextField, gridBagConstraints);

        examNameLbl.setText("Exam Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        examCreation_panel.add(examNameLbl, gridBagConstraints);

        cardlayout_container.add(examCreation_panel, "card7");

        examEdit_panel.setLayout(new java.awt.GridBagLayout());

        trueFalseFormAddEditBtn.setText("True / False Form");
        trueFalseFormAddEditBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        trueFalseFormAddEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueFalseFormAddEditBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.15;
        examEdit_panel.add(trueFalseFormAddEditBtn, gridBagConstraints);

        multipleChoiceFormAddEditBtn.setText("Multiple Choice Form");
        multipleChoiceFormAddEditBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        multipleChoiceFormAddEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleChoiceFormAddEditBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.weightx = 0.15;
        examEdit_panel.add(multipleChoiceFormAddEditBtn, gridBagConstraints);

        editReturnToTeacherPanelBtn.setText("Back To Teacher Panel");
        editReturnToTeacherPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editReturnToTeacherPanelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        examEdit_panel.add(editReturnToTeacherPanelBtn, gridBagConstraints);

        editExamFormBtn.setText("Update Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        examEdit_panel.add(editExamFormBtn, gridBagConstraints);

        examFormEditor_scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        examFormEditor_scrollPane.setPreferredSize(new java.awt.Dimension(300, 450));

        examFormEditor_panel.setLayout(new java.awt.GridLayout(0, 1, 0, 4));
        examFormEditor_scrollPane.setViewportView(examFormEditor_panel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.85;
        gridBagConstraints.weighty = 1.0;
        examEdit_panel.add(examFormEditor_scrollPane, gridBagConstraints);

        cardlayout_container.add(examEdit_panel, "card7");

        studentGrade_panel.setLayout(new java.awt.GridBagLayout());

        examGradeJList.setModel(new DefaultListModel<String>());
        examGrade_scrollpane.setViewportView(examGradeJList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        studentGrade_panel.add(examGrade_scrollpane, gridBagConstraints);

        cancelGradesBtn.setText("Go Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        studentGrade_panel.add(cancelGradesBtn, gridBagConstraints);

        cardlayout_container.add(studentGrade_panel, "card9");

        keyExam_panel.setLayout(new java.awt.GridBagLayout());

        examFormKey_scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        examFormKey_scrollPane.setHorizontalScrollBar(null);
        examFormKey_scrollPane.setPreferredSize(new java.awt.Dimension(525, 650));

        examFormKey_panel.setLayout(new java.awt.GridLayout(0, 1, 2, 4));
        examFormKey_scrollPane.setViewportView(examFormKey_panel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.85;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        keyExam_panel.add(examFormKey_scrollPane, gridBagConstraints);

        submitKeyBtn.setText("Submit Key");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        keyExam_panel.add(submitKeyBtn, gridBagConstraints);

        cancelKeyBtn.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        keyExam_panel.add(cancelKeyBtn, gridBagConstraints);

        cardlayout_container.add(keyExam_panel, "card11");

        teacherAssignExams_panel.setLayout(new java.awt.GridBagLayout());

        assignedStudents_jlist.setModel(new DefaultListModel<String>());
        assignedStudents_scrollpane.setViewportView(assignedStudents_jlist);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        teacherAssignExams_panel.add(assignedStudents_scrollpane, gridBagConstraints);

        studentsComboBox.setModel(new DefaultComboBoxModel<String>());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teacherAssignExams_panel.add(studentsComboBox, gridBagConstraints);

        cancelAssignExamBtn.setText("Back To Teacher Panel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        teacherAssignExams_panel.add(cancelAssignExamBtn, gridBagConstraints);

        assignStudentExamBtn.setText("Assign Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        teacherAssignExams_panel.add(assignStudentExamBtn, gridBagConstraints);

        cardlayout_container.add(teacherAssignExams_panel, "card10");

        getContentPane().add(cardlayout_container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void switchCardView(String cardName)
    {
        cardLayoutManager.show(cardlayout_container, cardName);
    }
    
    private void examCreationBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examCreationBackBtnActionPerformed
        cardLayoutManager.show(cardlayout_container, "teacher");
    }//GEN-LAST:event_examCreationBackBtnActionPerformed

    private void trueFalseFormAddEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueFalseFormAddEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trueFalseFormAddEditBtnActionPerformed

    private void multipleChoiceFormAddEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleChoiceFormAddEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multipleChoiceFormAddEditBtnActionPerformed

    private void editReturnToTeacherPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editReturnToTeacherPanelBtnActionPerformed
        cardLayoutManager.show(cardlayout_container, "teacher");
    }//GEN-LAST:event_editReturnToTeacherPanelBtnActionPerformed

    public JButton getCreateExamFormBtn() {
        return createExamFormBtn;
    }

    public JButton getDeleteExamBtn() {
        return deleteExamBtn;
    }

    public JLabel getRegister_incorrectPass_label() {
        return register_incorrectPass_label;
    }
    
    public JButton getCreateExamBtn() {
        return createExamBtn;
    }

    public JPanel getExamCreationFormPanel()
    {
        return examFormBuilder_panel;
    }
    
    public JButton getLoginButton()
    {
       return this.login_btn;
    }
    
    public JTextField getUsernameTextField()
    {
        return this.username_txtField;
    }
    
    /*public JPasswordField getPasswordTextField()
    {
        return this.password_txtField;
        //return String.valueOf(this.password_txtField.getPassword());
    }*/
    
    public CardLayout getCardLayoutManager()
    {
        return this.cardLayoutManager;
    }
    
    public JPanel getCardContainer()
    {
        return this.cardlayout_container;
    }
    
    public JButton getCancel_login_btn() {
        return cancel_login_btn;
    }

    
    public JPasswordField getPassword_txtField() {
        return password_txtField;
    }

    public JPasswordField getRegisterPasswordConfirm_txtField() {
        return registerPasswordConfirm_txtField;
    }

    public JPasswordField getRegisterPassword_txtField() {
        return registerPassword_txtField;
    }

    public JTextField getRegisterUsername_txtField() {
        return registerUsername_txtField;
    }

    public JButton getRegister_cancel_btn() {
        return register_cancel_btn;
    }

    public JTextField getUsername_txtField() {
        return username_txtField;
    }
    
     public JButton getRegister_btn() {
        return register_btn;
    }   
     
     public JComboBox<String> getUser_type_comboBox() {
        return user_type_comboBox;
    }    

    public JPanel getExamFormEditor_panel() {
        return examFormEditor_panel;
    }

    public JButton getMultipleChoiceFormAddBtn() {
        return multipleChoiceFormAddBtn;
    }

    public JButton getTrueFalseFormAddBtn() {
        return trueFalseFormAddBtn;
    }

    public JButton getStudentTakeExamBtn() {
        return studentTakeExamBtn;
    }

    public JTextField getCreateExamNameTextField() {
        return createExamNameTextField;
    }

    public JButton getEditReturnToTeacherPanelBtn() {
        return editReturnToTeacherPanelBtn;
    }

    public JButton getMultipleChoiceFormAddEditBtn() {
        return multipleChoiceFormAddEditBtn;
    }

    public JButton getTrueFalseFormAddEditBtn() {
        return trueFalseFormAddEditBtn;
    }

    public JButton getExamCreationBackBtn() {
        return examCreationBackBtn;
    }

    public JButton getKeyExamBtn() {
        return keyExamBtn;
    }

    public JPanel getExamFormKey_panel() {
        return examFormKey_panel;
    }

    public JButton getCancelKeyBtn() {
        return cancelKeyBtn;
    }

    public JButton getSubmitKeyBtn() {
        return submitKeyBtn;
    }

    public JButton getSubmitStudentExam() {
        return submitStudentExam;
    }

    public JButton getNewUserRegisterBtn() {
        return newUserRegisterBtn;
    }

    public JButton getAssignStudentExamBtn() {
        return assignStudentExamBtn;
    }

    public JButton getAssignExamButton() {
        return assignExamButton;
    }

    public JButton getStudentBackToLogin() {
        return studentBackToLogin;
    }

    public JButton getViewGradesBtn() {
        return viewGradesBtn;
    }

    public JList<String> getExamGradeJList() {
        return examGradeJList;
    }

    public JButton getCancelGradesBtn() {
        return cancelGradesBtn;
    }

    public JList<String> getAssignedStudents_jlist() {
        return assignedStudents_jlist;
    }

    public JComboBox<String> getStudentsComboBox() {
        return studentsComboBox;
    }

    public JPanel getTeacherAssignExams_panel() {
        return teacherAssignExams_panel;
    }

    public JButton getCancelAssignExamBtn() {
        return cancelAssignExamBtn;
    }

    public JButton getTeacherBackToLogin() {
        return teacherBackToLogin;
    }

    public JButton getCancelStudentExam() {
        return cancelStudentExam;
    }
    
    

    /**
     *
     * @return JPanel
     */
    public JPanel getExamFormContainer() {
        return examFormContainer;
    }
     
     public JButton getEditExamBtn() {
        return editExamBtn;
    }    
    
    public JButton getEditExamFormBtn() {
        return editExamFormBtn;
    } 
    
    public JList<String> getAvailableTeacherExams() {
        return availableTeacherExams;
    }    
    
    public JList<String> getAvailableStudentExams() {
        return availableStudentExams;
    }    
     
    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_Exam_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_Exam_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_Exam_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_Exam_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_Exam_Client_GUI().setVisible(true);
            }
        }); 
    }*/
   
     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignExamButton;
    private javax.swing.JButton assignStudentExamBtn;
    private javax.swing.JList<String> assignedStudents_jlist;
    private javax.swing.JScrollPane assignedStudents_scrollpane;
    private javax.swing.JList<String> availableStudentExams;
    private javax.swing.JList<String> availableTeacherExams;
    private javax.swing.JButton cancelAssignExamBtn;
    private javax.swing.JButton cancelGradesBtn;
    private javax.swing.JButton cancelKeyBtn;
    private javax.swing.JButton cancelStudentExam;
    private javax.swing.JButton cancel_login_btn;
    private javax.swing.JPanel cardlayout_container;
    private javax.swing.JButton createExamBtn;
    private javax.swing.JButton createExamFormBtn;
    private javax.swing.JTextField createExamNameTextField;
    private javax.swing.JButton deleteExamBtn;
    private javax.swing.JButton editExamBtn;
    private javax.swing.JButton editExamFormBtn;
    private javax.swing.JButton editReturnToTeacherPanelBtn;
    private javax.swing.JButton examCreationBackBtn;
    private javax.swing.JPanel examCreation_panel;
    private javax.swing.JPanel examEdit_panel;
    private javax.swing.JPanel examFormBuilder_panel;
    private javax.swing.JScrollPane examFormBuilder_scrollPane;
    private javax.swing.JPanel examFormContainer;
    private javax.swing.JPanel examFormEditor_panel;
    private javax.swing.JScrollPane examFormEditor_scrollPane;
    private javax.swing.JPanel examFormKey_panel;
    private javax.swing.JScrollPane examFormKey_scrollPane;
    private javax.swing.JList<String> examGradeJList;
    private javax.swing.JScrollPane examGrade_scrollpane;
    private javax.swing.JLabel examNameLbl;
    private javax.swing.JScrollPane examScrollPane;
    private javax.swing.JPanel exam_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keyExamBtn;
    private javax.swing.JPanel keyExam_panel;
    private javax.swing.JButton login_btn;
    private javax.swing.JPanel login_panel;
    private javax.swing.JButton multipleChoiceFormAddBtn;
    private javax.swing.JButton multipleChoiceFormAddEditBtn;
    private javax.swing.JButton newUserRegisterBtn;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPasswordField password_txtField;
    private javax.swing.JLabel registerConfirmPassword_lbl;
    private javax.swing.JPasswordField registerPasswordConfirm_txtField;
    private javax.swing.JLabel registerPassword_lbl;
    private javax.swing.JPasswordField registerPassword_txtField;
    private javax.swing.JLabel registerUsername_lbl;
    private javax.swing.JTextField registerUsername_txtField;
    private javax.swing.JButton register_btn;
    private javax.swing.JButton register_cancel_btn;
    private javax.swing.JLabel register_incorrectPass_label;
    private javax.swing.JPanel register_panel;
    private javax.swing.JButton studentBackToLogin;
    private javax.swing.JPanel studentGrade_panel;
    private javax.swing.JButton studentTakeExamBtn;
    private javax.swing.JPanel student_panel;
    private javax.swing.JComboBox<String> studentsComboBox;
    private javax.swing.JButton submitKeyBtn;
    private javax.swing.JButton submitStudentExam;
    private javax.swing.JPanel teacherAssignExams_panel;
    private javax.swing.JButton teacherBackToLogin;
    private javax.swing.JPanel teacher_panel;
    private javax.swing.JButton trueFalseFormAddBtn;
    private javax.swing.JButton trueFalseFormAddEditBtn;
    private javax.swing.JComboBox<String> user_type_comboBox;
    private javax.swing.JLabel user_type_lbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JTextField username_txtField;
    private javax.swing.JButton viewGradesBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
