/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oopgroup3.e_exam_client;


import com.oopgroup3.e_exam_client.ExamQuestionClasses.ExamFormCreationManager;
import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Kyle
 */
public class E_Exam_Client_GUI extends javax.swing.JFrame {

    private final CardLayout cardLayoutManager;
    private boolean  doonce = true;
    /**
     * Creates new form EExam_GUI
     */
    public E_Exam_Client_GUI() {
        initComponents();
       
        cardLayoutManager = (CardLayout)cardlayout_container.getLayout();
        
        cardlayout_container.add(login_panel, "login");
        cardlayout_container.add(register_panel, "register");
        cardlayout_container.add(student_panel, "student");
        cardlayout_container.add(teacher_panel, "teacher");
        cardlayout_container.add(exam_panel, "exam");
        cardlayout_container.add(examCreation_panel, "createExam");
        cardlayout_container.add(examEdit_panel, "editExam");
        
        cardLayoutManager.show(cardlayout_container, "login");
        setTitle("E-Exam");
        pack();
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cardlayout_container = new javax.swing.JPanel();
        login_panel = new javax.swing.JPanel();
        username_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        cancel_login_btn = new javax.swing.JButton();
        username_txtField = new javax.swing.JTextField();
        password_txtField = new javax.swing.JPasswordField();
        gotoRegisterPanel = new javax.swing.JButton();
        gotoStudentPanel = new javax.swing.JButton();
        gotoTeacherPanel = new javax.swing.JButton();
        register_panel = new javax.swing.JPanel();
        registerUsername_lbl = new javax.swing.JLabel();
        registerPassword_lbl = new javax.swing.JLabel();
        registerConfirmPassword_lbl = new javax.swing.JLabel();
        register_btn = new javax.swing.JButton();
        register_cancel_btn = new javax.swing.JButton();
        registerUsername_txtField = new javax.swing.JTextField();
        registerPassword_txtField = new javax.swing.JPasswordField();
        registerPasswordConfirm_txtField = new javax.swing.JPasswordField();
        backToLogin = new javax.swing.JButton();
        user_type_comboBox = new javax.swing.JComboBox<>();
        user_type_lbl = new javax.swing.JLabel();
        register_incorrectPass_label = new javax.swing.JLabel();
        student_panel = new javax.swing.JPanel();
        studentBackToLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableStudentExams = new javax.swing.JList<>();
        welcomeLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        studentTakeExamBtn = new javax.swing.JButton();
        teacher_panel = new javax.swing.JPanel();
        teacherBackToLogin = new javax.swing.JButton();
        createExamBtn = new javax.swing.JButton();
        editExamBtn = new javax.swing.JButton();
        deleteExamBtn = new javax.swing.JButton();
        assignExamButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        availableTeacherExams = new javax.swing.JList<>();
        exam_panel = new javax.swing.JPanel();
        examBackToLogin = new javax.swing.JButton();
        examScrollPane = new javax.swing.JScrollPane();
        examFormContainer = new javax.swing.JPanel();
        submitStudentExam = new javax.swing.JButton();
        cancelStudentExam = new javax.swing.JButton();
        examCreation_panel = new javax.swing.JPanel();
        trueFalseFormAddBtn = new javax.swing.JButton();
        multipleChoiceFormAddBtn = new javax.swing.JButton();
        examCreationBackBtn = new javax.swing.JButton();
        createExamFormBtn = new javax.swing.JButton();
        examFormBuilder_scrollPane = new javax.swing.JScrollPane();
        examFormBuilder_panel = new javax.swing.JPanel();
        createExamNameTextField = new javax.swing.JTextField();
        examNameLbl = new javax.swing.JLabel();
        examEdit_panel = new javax.swing.JPanel();
        trueFalseFormAddEditBtn = new javax.swing.JButton();
        multipleChoiceFormAddEditBtn = new javax.swing.JButton();
        editReturnToTeacherPanelBtn = new javax.swing.JButton();
        editExamFormBtn = new javax.swing.JButton();
        examFormEditor_scrollPane = new javax.swing.JScrollPane();
        examFormEditor_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardlayout_container.setLayout(new java.awt.CardLayout());

        login_panel.setLayout(new java.awt.GridBagLayout());

        username_lbl.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 0);
        login_panel.add(username_lbl, gridBagConstraints);

        password_lbl.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 62, 0, 0);
        login_panel.add(password_lbl, gridBagConstraints);

        login_btn.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 90);
        login_panel.add(login_btn, gridBagConstraints);

        cancel_login_btn.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 65, 0, 88);
        login_panel.add(cancel_login_btn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 90);
        login_panel.add(username_txtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 90);
        login_panel.add(password_txtField, gridBagConstraints);

        gotoRegisterPanel.setText("To Register Panel");
        gotoRegisterPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoRegisterPanelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        login_panel.add(gotoRegisterPanel, gridBagConstraints);

        gotoStudentPanel.setText("To Student Panel");
        gotoStudentPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoStudentPanelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        login_panel.add(gotoStudentPanel, gridBagConstraints);

        gotoTeacherPanel.setText("To Teacher Panel");
        gotoTeacherPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoTeacherPanelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        login_panel.add(gotoTeacherPanel, gridBagConstraints);

        cardlayout_container.add(login_panel, "card2");

        register_panel.setLayout(new java.awt.GridBagLayout());

        registerUsername_lbl.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        register_panel.add(registerUsername_lbl, gridBagConstraints);

        registerPassword_lbl.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        register_panel.add(registerPassword_lbl, gridBagConstraints);

        registerConfirmPassword_lbl.setText("Confirm Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        register_panel.add(registerConfirmPassword_lbl, gridBagConstraints);

        register_btn.setText("Register");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        register_panel.add(register_btn, gridBagConstraints);

        register_cancel_btn.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        register_panel.add(register_cancel_btn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        register_panel.add(registerUsername_txtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        register_panel.add(registerPassword_txtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        register_panel.add(registerPasswordConfirm_txtField, gridBagConstraints);

        backToLogin.setText("Back To Login");
        backToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        register_panel.add(backToLogin, gridBagConstraints);

        user_type_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        register_panel.add(user_type_comboBox, gridBagConstraints);

        user_type_lbl.setText("User Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        register_panel.add(user_type_lbl, gridBagConstraints);

        register_incorrectPass_label.setForeground(new java.awt.Color(204, 0, 0));
        register_incorrectPass_label.setText("Incorrect password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        register_panel.add(register_incorrectPass_label, gridBagConstraints);

        cardlayout_container.add(register_panel, "card3");

        student_panel.setLayout(new java.awt.GridBagLayout());

        studentBackToLogin.setText("Back To Login");
        studentBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBackToLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        student_panel.add(studentBackToLogin, gridBagConstraints);

        availableStudentExams.setModel(new DefaultListModel<String>());
        jScrollPane1.setViewportView(availableStudentExams);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.25;
        student_panel.add(jScrollPane1, gridBagConstraints);

        welcomeLbl.setText("Welcome to E-Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        student_panel.add(welcomeLbl, gridBagConstraints);

        usernameLbl.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        student_panel.add(usernameLbl, gridBagConstraints);

        studentTakeExamBtn.setText("Take Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        student_panel.add(studentTakeExamBtn, gridBagConstraints);

        cardlayout_container.add(student_panel, "card4");

        teacher_panel.setLayout(new java.awt.GridBagLayout());

        teacherBackToLogin.setText("Back To Login");
        teacherBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherBackToLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        teacher_panel.add(teacherBackToLogin, gridBagConstraints);

        createExamBtn.setText("Create Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teacher_panel.add(createExamBtn, gridBagConstraints);

        editExamBtn.setText("Edit Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teacher_panel.add(editExamBtn, gridBagConstraints);

        deleteExamBtn.setText("Delete Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teacher_panel.add(deleteExamBtn, gridBagConstraints);

        assignExamButton.setText("Assign Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 120, 0);
        teacher_panel.add(assignExamButton, gridBagConstraints);

        availableTeacherExams.setModel(new DefaultListModel<String>());
        jScrollPane2.setViewportView(availableTeacherExams);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.85;
        gridBagConstraints.weighty = 1.0;
        teacher_panel.add(jScrollPane2, gridBagConstraints);

        cardlayout_container.add(teacher_panel, "card5");

        exam_panel.setLayout(new java.awt.GridBagLayout());

        examBackToLogin.setText("Back To Login");
        examBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examBackToLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        exam_panel.add(examBackToLogin, gridBagConstraints);

        examFormContainer.setPreferredSize(new java.awt.Dimension(366, 222));
        examFormContainer.setLayout(new java.awt.GridLayout(0, 1));
        examScrollPane.setViewportView(examFormContainer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        exam_panel.add(examScrollPane, gridBagConstraints);

        submitStudentExam.setText("Submit Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 0);
        exam_panel.add(submitStudentExam, gridBagConstraints);

        cancelStudentExam.setText("Cancel Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 70);
        exam_panel.add(cancelStudentExam, gridBagConstraints);

        cardlayout_container.add(exam_panel, "card6");

        examCreation_panel.setLayout(new java.awt.GridBagLayout());

        trueFalseFormAddBtn.setText("True / False Form");
        trueFalseFormAddBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.15;
        examCreation_panel.add(trueFalseFormAddBtn, gridBagConstraints);

        multipleChoiceFormAddBtn.setText("Multiple Choice Form");
        multipleChoiceFormAddBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.weightx = 0.15;
        examCreation_panel.add(multipleChoiceFormAddBtn, gridBagConstraints);

        examCreationBackBtn.setText("Back To Teach Panel");
        examCreationBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examCreationBackBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        examCreation_panel.add(examCreationBackBtn, gridBagConstraints);

        createExamFormBtn.setText("Create Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        examCreation_panel.add(createExamFormBtn, gridBagConstraints);

        examFormBuilder_scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        examFormBuilder_scrollPane.setHorizontalScrollBar(null);
        examFormBuilder_scrollPane.setPreferredSize(new java.awt.Dimension(525, 650));

        examFormBuilder_panel.setLayout(new java.awt.GridLayout(0, 1, 2, 4));
        examFormBuilder_scrollPane.setViewportView(examFormBuilder_panel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.85;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        examCreation_panel.add(examFormBuilder_scrollPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        examCreation_panel.add(createExamNameTextField, gridBagConstraints);

        examNameLbl.setText("Exam Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        examCreation_panel.add(examNameLbl, gridBagConstraints);

        cardlayout_container.add(examCreation_panel, "card7");

        examEdit_panel.setLayout(new java.awt.GridBagLayout());

        trueFalseFormAddEditBtn.setText("True / False Form");
        trueFalseFormAddEditBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        trueFalseFormAddEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueFalseFormAddEditBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.15;
        examEdit_panel.add(trueFalseFormAddEditBtn, gridBagConstraints);

        multipleChoiceFormAddEditBtn.setText("Multiple Choice Form");
        multipleChoiceFormAddEditBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        multipleChoiceFormAddEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleChoiceFormAddEditBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.weightx = 0.15;
        examEdit_panel.add(multipleChoiceFormAddEditBtn, gridBagConstraints);

        editReturnToTeacherPanelBtn.setText("Back To Teacher Panel");
        editReturnToTeacherPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editReturnToTeacherPanelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        examEdit_panel.add(editReturnToTeacherPanelBtn, gridBagConstraints);

        editExamFormBtn.setText("Update Exam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        examEdit_panel.add(editExamFormBtn, gridBagConstraints);

        examFormEditor_scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        examFormEditor_scrollPane.setPreferredSize(new java.awt.Dimension(300, 450));

        examFormEditor_panel.setLayout(new java.awt.GridLayout(0, 1, 0, 4));
        examFormEditor_scrollPane.setViewportView(examFormEditor_panel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.85;
        gridBagConstraints.weighty = 1.0;
        examEdit_panel.add(examFormEditor_scrollPane, gridBagConstraints);

        cardlayout_container.add(examEdit_panel, "card7");

        getContentPane().add(cardlayout_container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotoRegisterPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoRegisterPanelActionPerformed
        cardLayoutManager.show(cardlayout_container, "register");
        this.register_incorrectPass_label.setVisible(false);
    }//GEN-LAST:event_gotoRegisterPanelActionPerformed

    private void backToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginActionPerformed
        cardLayoutManager.show(cardlayout_container, "login");
    }//GEN-LAST:event_backToLoginActionPerformed

    private void studentBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBackToLoginActionPerformed
        cardLayoutManager.show(cardlayout_container, "login");
    }//GEN-LAST:event_studentBackToLoginActionPerformed

    private void gotoStudentPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoStudentPanelActionPerformed
        cardLayoutManager.show(cardlayout_container, "student");
    }//GEN-LAST:event_gotoStudentPanelActionPerformed

    private void teacherBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherBackToLoginActionPerformed
        cardLayoutManager.show(cardlayout_container, "login");
    }//GEN-LAST:event_teacherBackToLoginActionPerformed

    private void gotoTeacherPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoTeacherPanelActionPerformed
        ExamFormCreationManager.getInstanceExamFormCreationManager().setRootPanel(examFormBuilder_panel);
        cardLayoutManager.show(cardlayout_container, "teacher");
    }//GEN-LAST:event_gotoTeacherPanelActionPerformed

    private void examBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examBackToLoginActionPerformed
        cardLayoutManager.show(cardlayout_container, "login");
    }//GEN-LAST:event_examBackToLoginActionPerformed

    public void switchCardView(String cardName)
    {
        cardLayoutManager.show(cardlayout_container, cardName);
    }
    
    private void examCreationBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examCreationBackBtnActionPerformed
        cardLayoutManager.show(cardlayout_container, "teacher");
    }//GEN-LAST:event_examCreationBackBtnActionPerformed

    private void trueFalseFormAddEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueFalseFormAddEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trueFalseFormAddEditBtnActionPerformed

    private void multipleChoiceFormAddEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleChoiceFormAddEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multipleChoiceFormAddEditBtnActionPerformed

    private void editReturnToTeacherPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editReturnToTeacherPanelBtnActionPerformed
        cardLayoutManager.show(cardlayout_container, "teacher");
    }//GEN-LAST:event_editReturnToTeacherPanelBtnActionPerformed

    public JButton getCreateExamFormBtn() {
        return createExamFormBtn;
    }

    public JButton getDeleteExamBtn() {
        return deleteExamBtn;
    }

    public JLabel getRegister_incorrectPass_label() {
        return register_incorrectPass_label;
    }
    
    public JButton getCreateExamBtn() {
        return createExamBtn;
    }

    public JPanel getExamCreationFormPanel()
    {
        return examFormBuilder_panel;
    }
    
    public JButton getLoginButton()
    {
       return this.login_btn;
    }
    
    public JTextField getUsernameTextField()
    {
        return this.username_txtField;
    }
    
    /*public JPasswordField getPasswordTextField()
    {
        return this.password_txtField;
        //return String.valueOf(this.password_txtField.getPassword());
    }*/
    
    public CardLayout getCardLayoutManager()
    {
        return this.cardLayoutManager;
    }
    
    public JPanel getCardContainer()
    {
        return this.cardlayout_container;
    }
    
    public JButton getCancel_login_btn() {
        return cancel_login_btn;
    }

    
    public JPasswordField getPassword_txtField() {
        return password_txtField;
    }

    public JPasswordField getRegisterPasswordConfirm_txtField() {
        return registerPasswordConfirm_txtField;
    }

    public JPasswordField getRegisterPassword_txtField() {
        return registerPassword_txtField;
    }

    public JTextField getRegisterUsername_txtField() {
        return registerUsername_txtField;
    }

    public JButton getRegister_cancel_btn() {
        return register_cancel_btn;
    }

    public JTextField getUsername_txtField() {
        return username_txtField;
    }
    
     public JButton getRegister_btn() {
        return register_btn;
    }   
     
     public JComboBox<String> getUser_type_comboBox() {
        return user_type_comboBox;
    }    

    public JPanel getExamFormEditor_panel() {
        return examFormEditor_panel;
    }

    public JButton getMultipleChoiceFormAddBtn() {
        return multipleChoiceFormAddBtn;
    }

    public JButton getTrueFalseFormAddBtn() {
        return trueFalseFormAddBtn;
    }

    public JButton getStudentTakeExamBtn() {
        return studentTakeExamBtn;
    }

    public JTextField getCreateExamNameTextField() {
        return createExamNameTextField;
    }

    public JButton getEditReturnToTeacherPanelBtn() {
        return editReturnToTeacherPanelBtn;
    }

    public JButton getMultipleChoiceFormAddEditBtn() {
        return multipleChoiceFormAddEditBtn;
    }

    public JButton getTrueFalseFormAddEditBtn() {
        return trueFalseFormAddEditBtn;
    }

    public JButton getExamCreationBackBtn() {
        return examCreationBackBtn;
    }
     
    
    
     
    /**
     *
     * @return JPanel
     */
    public JPanel getExamFormContainer() {
        return examFormContainer;
    }
     
     public JButton getEditExamBtn() {
        return editExamBtn;
    }    
    
    public JButton getEditExamFormBtn() {
        return editExamFormBtn;
    } 
    
    public JList<String> getAvailableTeacherExams() {
        return availableTeacherExams;
    }    
    
    public JList<String> getAvailableStudentExams() {
        return availableStudentExams;
    }    
     
    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_Exam_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_Exam_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_Exam_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_Exam_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_Exam_Client_GUI().setVisible(true);
            }
        }); 
    }*/






    









     
     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignExamButton;
    private javax.swing.JList<String> availableStudentExams;
    private javax.swing.JList<String> availableTeacherExams;
    private javax.swing.JButton backToLogin;
    private javax.swing.JButton cancelStudentExam;
    private javax.swing.JButton cancel_login_btn;
    private javax.swing.JPanel cardlayout_container;
    private javax.swing.JButton createExamBtn;
    private javax.swing.JButton createExamFormBtn;
    private javax.swing.JTextField createExamNameTextField;
    private javax.swing.JButton deleteExamBtn;
    private javax.swing.JButton editExamBtn;
    private javax.swing.JButton editExamFormBtn;
    private javax.swing.JButton editReturnToTeacherPanelBtn;
    private javax.swing.JButton examBackToLogin;
    private javax.swing.JButton examCreationBackBtn;
    private javax.swing.JPanel examCreation_panel;
    private javax.swing.JPanel examEdit_panel;
    private javax.swing.JPanel examFormBuilder_panel;
    private javax.swing.JScrollPane examFormBuilder_scrollPane;
    private javax.swing.JPanel examFormContainer;
    private javax.swing.JPanel examFormEditor_panel;
    private javax.swing.JScrollPane examFormEditor_scrollPane;
    private javax.swing.JLabel examNameLbl;
    private javax.swing.JScrollPane examScrollPane;
    private javax.swing.JPanel exam_panel;
    private javax.swing.JButton gotoRegisterPanel;
    private javax.swing.JButton gotoStudentPanel;
    private javax.swing.JButton gotoTeacherPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton login_btn;
    private javax.swing.JPanel login_panel;
    private javax.swing.JButton multipleChoiceFormAddBtn;
    private javax.swing.JButton multipleChoiceFormAddEditBtn;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPasswordField password_txtField;
    private javax.swing.JLabel registerConfirmPassword_lbl;
    private javax.swing.JPasswordField registerPasswordConfirm_txtField;
    private javax.swing.JLabel registerPassword_lbl;
    private javax.swing.JPasswordField registerPassword_txtField;
    private javax.swing.JLabel registerUsername_lbl;
    private javax.swing.JTextField registerUsername_txtField;
    private javax.swing.JButton register_btn;
    private javax.swing.JButton register_cancel_btn;
    private javax.swing.JLabel register_incorrectPass_label;
    private javax.swing.JPanel register_panel;
    private javax.swing.JButton studentBackToLogin;
    private javax.swing.JButton studentTakeExamBtn;
    private javax.swing.JPanel student_panel;
    private javax.swing.JButton submitStudentExam;
    private javax.swing.JButton teacherBackToLogin;
    private javax.swing.JPanel teacher_panel;
    private javax.swing.JButton trueFalseFormAddBtn;
    private javax.swing.JButton trueFalseFormAddEditBtn;
    private javax.swing.JComboBox<String> user_type_comboBox;
    private javax.swing.JLabel user_type_lbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JTextField username_txtField;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
